[package]
name = "manif"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = {version="0.32.3", features=["compare"]}
[dev-dependencies]
rand = "0.8"
matrixcompare = "0.3.0"
